### Test successful login (local)
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "secret"
}

###

### Test failed login (local)
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "wrong",
  "password": "incorrect"
}

###

### Test successful login (Azure deployment)
POST https://flask-login-app-gbh5b0agehhcdyfm.canadacentral-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "secret"
}

###

### Test failed login (Azure deployment)
POST https://flask-login-app-gbh5b0agehhcdyfm.canadacentral-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "wrong",
  "password": "incorrect"
}
